# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('phonenum', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=20)),
            ],
        ),
    ]
